server:
  port: 8089

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8080/api/v1/customers
          predicates:
            - Path=/api/v1/customers/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost